#!/usr/bin/env bash
#
# verify-urls.sh — live check of the site's URL contract.
#
# Asserts the bilingual + no-trailing-slash URL contract against a live base URL
# (a Cloudflare *.pages.dev preview or the production https://michelmoreira.eti.br).
#
# URL contract: `/en` (NO trailing slash) is the canonical EN home.
#   - `/`     → 200 (PT home, default locale, unprefixed)
#   - `/en`   → 200 (EN home, canonical no-trailing-slash)
#   - `/en/`  → a 3xx redirect whose Location resolves to `/en` (alias only)
#
# Redirects are OBSERVED, not followed (curl does not follow location redirects),
# so the raw status of each path is asserted directly. The script is reusable
# against both preview and production URLs.
#
# Usage: scripts/verify-urls.sh https://<hash>.pages.dev
#        scripts/verify-urls.sh https://michelmoreira.eti.br

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <base-url>   e.g. $0 https://<hash>.pages.dev" >&2
  exit 2
fi

# Normalise: strip any trailing slash from the supplied base URL.
BASE="${1%/}"

fail=0

# Return the raw HTTP status code for a URL WITHOUT following redirects.
# On a connection/DNS failure curl emits "000" — treat that as an unreachable host.
http_status() {
  curl -sS -o /dev/null -w '%{http_code}' "$1" 2>/dev/null || true
}

# Return the Location header for a URL WITHOUT following redirects.
location_header() {
  curl -sS -o /dev/null -D - "$1" 2>/dev/null \
    | tr -d '\r' \
    | awk 'tolower($1) == "location:" { print $2 }' \
    | tail -n1
}

# --- Assert: ${BASE}/ → 200 (PT home) ---
root_code="$(http_status "${BASE}/" )"
if [ "$root_code" = "200" ]; then
  echo "PASS  ${BASE}/  → 200 (PT home)"
else
  echo "FAIL  ${BASE}/  → ${root_code} (expected 200 — PT home)" >&2
  fail=1
fi

# --- Assert: ${BASE}/en → 200 (EN home, canonical no trailing slash) ---
en_code="$(http_status "${BASE}/en" )"
if [ "$en_code" = "200" ]; then
  echo "PASS  ${BASE}/en  → 200 (EN home, canonical)"
else
  echo "FAIL  ${BASE}/en  → ${en_code} (expected 200 — canonical EN home)" >&2
  fail=1
fi

# --- Assert: ${BASE}/en/ → 3xx redirect to canonical /en (308 expected) ---
ens_code="$(http_status "${BASE}/en/" )"
if [ "$ens_code" = "308" ] || { [ "$ens_code" -ge 300 ] 2>/dev/null && [ "$ens_code" -lt 400 ] 2>/dev/null; }; then
  loc="$(location_header "${BASE}/en/" || true)"
  # Accept an absolute or relative Location as long as it resolves to /en (no trailing slash).
  loc_path="${loc#"${BASE}"}"
  loc_path="${loc_path%/}"
  if [ "$loc_path" = "/en" ]; then
    echo "PASS  ${BASE}/en/  → ${ens_code} → ${loc} (redirects to canonical /en)"
  else
    echo "FAIL  ${BASE}/en/  → ${ens_code} but Location='${loc}' (expected to end in /en)" >&2
    fail=1
  fi
elif [ "$ens_code" = "404" ]; then
  # Cloudflare Pages normally serves the trailing-slash alias as a 308 redirect
  # to the canonical extensionless path. If it 404s instead, an explicit
  # one-line public/_redirects rule ("/en/  /en  308") restores the contract.
  echo "FAIL  ${BASE}/en/  → 404 (no redirect to canonical /en)" >&2
  echo "      DIAGNOSTIC: Cloudflare is not redirecting /en/ → /en." >&2
  echo "      FIX: add to public/_redirects:  /en/  /en  308" >&2
  fail=1
else
  echo "FAIL  ${BASE}/en/  → ${ens_code} (expected a 3xx redirect to /en)" >&2
  fail=1
fi

# --- Assert: 200 on every Phase 3 page pair (PT localized slug + EN slug) ---
# RED until each plan ships its page (mirrors the Phase 2 verify-design.sh
# RED-first anchor): /uses is live from this plan; /curriculo, /en/resume,
# /portfolio, /en/portfolio, /now, /en/now land in later plans. This loop is
# the phase's URL-contract gate — it grows to green as each page ships, never
# rewritten path by path.
phase3_paths=(
  "/curriculo"
  "/en/resume"
  "/portfolio"
  "/en/portfolio"
  "/uses"
  "/en/uses"
  "/now"
  "/en/now"
)
for path in "${phase3_paths[@]}"; do
  code="$(http_status "${BASE}${path}")"
  if [ "$code" = "200" ]; then
    echo "PASS  ${BASE}${path}  → 200"
  else
    echo "FAIL  ${BASE}${path}  → ${code} (expected 200)" >&2
    fail=1
  fi
done

# --- Assert: 200 on both per-language resume PDF assets (PAGE-03) ---
# Generated by the resume-pdf.yml workflow and committed to public/; these
# are the exact files the /curriculo and /en/resume download links point at.
pdf_paths=(
  "/michel-moreira-cv-pt.pdf"
  "/michel-moreira-cv-en.pdf"
)
for path in "${pdf_paths[@]}"; do
  code="$(http_status "${BASE}${path}")"
  if [ "$code" = "200" ]; then
    echo "PASS  ${BASE}${path}  → 200"
  else
    echo "FAIL  ${BASE}${path}  → ${code} (expected 200)" >&2
    fail=1
  fi
done

if [ "$fail" -ne 0 ]; then
  echo "" >&2
  echo "verify-urls: FAILED — the bilingual / no-trailing-slash contract is not satisfied at ${BASE}" >&2
  exit 1
fi

echo ""
echo "verify-urls: PASSED — /, /en (200), /en/ (redirect → /en), all Phase 3 page pairs, and both resume PDFs green at ${BASE}"
